const data = {
  works: [
    {
      id: 'la-piba-berreta',
      title: 'lapibaberreta.com',
      url: 'https://lapibaberreta.com',
      year: 2026,
    },
    {
      id: "heidi-giel",
      title: "heidigiel.com",
      url: "https://heidigiel.com",
      year: 2025,
    },
    {
      id: "aguja",
      title: "aguja6167756a61.github.io",
      url: "https://aguja6167756a61.github.io",
      year: 2025,
    },
    {
      id: "clara-bunge",
      title: "clarabunge.com",
      url: "https://clarabunge.com",
      year: 2025,
    },
    {
      id: "princesa-vampiro",
      title: "princesavampiro.com",
      url: "https://princesavampiro.com",
      year: 2025,
    },
    {
      id: "terra-ignota-map",
      title: "map.nicolasspencer.com",
      url: "https://map.nicolasspencer.com",
      year: 2025,
    },
    {
      id: 1,
      title: "florenciacurci.xyz",
      details: "",
      url: "https://florenciacurci.xyz",
      year: 2024,
    },
    {
      id: 2,
      title: "sebastianschjaer.com",
      details: "",
      url: "https://www.sebastianschjaer.com",
      year: 2024,
    },
    {
      id: 3,
      title: "gregorionash.com",
      details: "",
      url: "https://www.gregorionash.com",
      year: 2024,
    },
    // {
    //   id: 4,
    //   title: "radiocaso.xyz",
    //   details: { en: "under construction", es: "en construccion" },
    //   url: "https://www.radiocaso.xyz",
    //   year: 2024,
    // },
    {
      id: 5,
      title: "omu.astrosuka.xyz",
      details: "",
      url: "https://omu.astrosuka.xyz",
      year: 2024,
    },
    // {
    //   id: 6,
    //   title: "sofja.uno",
    //   details: "",
    //   url: "https://sofja.uno",
    //   year: 2024,
    // },
    // {
    //   id: 7,
    //   title: "aguja.re",
    //   details: { en: "experimental", es: "experimental" },
    //   url: "https://aguja.re",
    //   year: 2024,
    // },
    // {
    //   id: 8,
    //   title: "diegogalloti.com",
    //   details: "",
    //   url: "https://diegogallotti.com",
    //   year: 2024,
    // },
    // {
    //   id: 9,
    //   title: "astrosuka-old.vercel.app",
    //   details: { en: "archived", es: "archivado" },
    //   url: "https://astrosuka-old.vercel.app",
    //   year: 2020,
    // },
    // {
    //   id: 10,
    //   title: "ceciliacastro.net",
    //   details: "",
    //   url: "http://ceciliacastro.net",
    //   year: 2020,
    // },
    // {
    //   id: 11,
    //   title: "trrueno.vercel.app",
    //   details: { en: "archived", es: "archivado" },
    //   url: "https://trrueno.vercel.app",
    //   year: 2020,
    // },
    // {
    //   id: 12,
    //   title: "solo flyers",
    //   details: { en: "under construction", es: "en construccion" },
    //   url: "https://satira-hub.github.io/solo_flyers/",
    //   year: 2025,
    // },
  ],
};

export default data;
